import { SiteHeader } from "../components/SiteHeader";

function Brand() {
  return <span className="brand-lockup" aria-label="CriativAI"><img className="brand-logo" src="/logo.svg" alt="" aria-hidden="true" /></span>;
}

const awards = [
  { award: "Original Prompt Engineer Technique", title: "🥇 1st place at FlowGPT.com", image: "CPT_TUB.jpg", alt: "Concatenated Prompt Technique", text: "It is a new approach to prompt creation that enables ChatGPT to run multiple prompts in a single input, making it easier to expand prompt functionalities and allowing the model to handle much more complex and intricate interactions resembling app or website functionality (Prompt App).", links: [["Competition results page", "https://flowgpt.com/bounty/s3-original-prompt-techniques"], ["Direct access link to the winning prompt", "https://flowgpt.com/p/cpt-concatenated-prompt-technique-4"]] },
  { award: "Prompt Engineer - Hackathon", title: "🥇 1st place at Chipp.ai Hackathon", image: "2024/09/CPT_TUB_AGENTOS.jpg", alt: "AgentOS, Multi tasking AI Agent", text: "AgentOS is the first personalized Multi-Tasking AI Agent, capable of executing multiple internal and external functions simultaneously from a single prompt input.", links: [["Chipp.ai - Competition results page", "https://chipp.substack.com/p/chipp-hackathon-winners-showcase"], ["Direct access link to AgentOS (winning AI Agent)", "https://agentos-12981.chipp.ai/"]] },
  { award: "Inovative category | bulit-in chatgpt Game", title: "🥇 1st place at FlowGPT Prompt Battle", image: "TIME_TUB.jpg", alt: "Track to the Future game", text: "Track to the Future Game stars the Cybertrack Quantum SUV by Elon Musk, designed to reveal life's secrets and why humanity is controlled. With Quantum Technology, it traverses time to explore quantum scenarios for humanity's benefit.", links: [["Competition results page", "https://flowgpt.com/bounty/past-and-future"], ["Direct access link to the winning prompt", "https://flowgpt.com/p/track-to-the-future-game-1"]] },
  { award: "Prompt Engineer | Judge Category", title: "🥈 2nd place at FlowGPT Hackathon", image: "TUB_JUDGEN.jpg", alt: "AI Judgen ChatGPT prompt", text: "JUDGEN is a prompt judge that evaluates and provides grades for different aspects of a given prompt. It assesses creativity, clarity and input precision, originality, syntax consistency, logical structure, and identifies negative points in the prompt.", links: [["Competition results page", "https://flowgpt.com/bounty/s3-chatgpt-judge"], ["Direct access link to the winning prompt", "https://flowgpt.com/p/judgen-ai-1"]] },
  { award: "Innovative ChatGPT Built-In Game", title: "🏅 Finalist at FlowGPT Prompt Battle", image: "MINECRAFT_MASHUP_CHATGPT_GAME.jpg", alt: "Minecraft Mashup Game", text: "Embark on an epic journey to discover the final secret Beyond THE END Minecraft Game, discover its hidden messages, talk to Herobrine, reveal the secret behind this mysterious entity, and play with iconic game characters.", links: [["Competition results page", "https://flowgpt.com/bounty/promptBattle0724"], ["Direct access link to the winning prompt", "https://flowgpt.com/p/nM8rkh83STfc2UIE4E9xj"]] },
  { award: "Innovative ChatGPT Built-In Game", title: "🏅 Finalist at FlowGPT Prompt Battle", image: "SHERLOCK_TUB.jpg", alt: "Sherlock Hoax game", text: "A jailbroken ChatGPT themed investigation game where you are free to talk about conspiracy theory subjects. Meet Sherlock Hoax, James Bomb, and Dr. Straaange, each with a specific ability to help you see different aspects of your topic.", links: [["Direct access link to the winning prompt", "https://flowgpt.com/p/sherlock-hoax-game"]] },
  { award: "Creative Category", title: "🥉 3rd place at FlowGPT Hackathon S2", image: "GPTINDER_Brazil.jpg", alt: "GPTinder Creative ChatGPT Prompt Engineering", text: "GPTinder will help you formulate the best phrases to conquer your favorite crush in any dating app. It asks for user and crush information and automatically creates interesting phrases and personalized subjects.", links: [["Competition results page", "https://flowgpt.com/bounty/hMydz_Vg7yIIoRQ8wK1y-"], ["Direct access link to the winning prompt", "https://flowgpt.com/p/gptinder-your-turbocharged-dating-advisor-16"]] },
  { award: "Software Development", title: "🥉 3rd place at FlowGPT Hackathon S2", image: "TUB_ICON_v2.jpg", alt: "ICON Machine Unicode Icon Discovery tool", text: "The first icon app for ChatGPT. Bring any icon reference and it discovers related icons, including official names and everything needed to deploy Unicode icons in a simple, functional table.", links: [["Competition results page", "https://flowgpt.com/bounty/xa_9CI5A41wMta9FTyTET"], ["Direct access link to the winning prompt", "https://flowgpt.com/p/icon-machine-is-everything-you-need-to-deal-with-icons-4-any-application-2"]] },
] as const;

export default function AwardsPage() {
  return <main className="awards-page" id="top"><SiteHeader brand={<Brand />} page="awards" /><article className="awards-article site-container"><header className="cpt-article__header"><p className="eyebrow">Prompt Engineering</p><h1 className="awards-title"><span className="awards-title__text">AWARDS</span></h1><p>During my research, I decided to put my acquired knowledge to the test by participating in hackathons. Immersing myself in international competitions and viewing each one as a chance to push the boundaries of AI innovation has driven me to craft sophisticated, advanced, and precise prompt submissions, resulting in some remarkable achievements. Here are some awards and recognitions from prompt engineering hackathons:</p></header>{awards.map((item) => <section className="award-item" key={item.title}><p className="eyebrow">{item.award}</p><div className="award-item__grid"><img src={`https://pmt.criativai.site/wp-content/uploads/${item.image.includes("/") ? item.image : `2024/03/${item.image}`}`} alt={item.alt} loading="lazy" /><div><h2>{item.title}</h2><p>{item.text}</p>{item.links.map(([label, url]) => <p key={url}>{label}:<br /><a href={url} target="_blank" rel="noreferrer">{url}</a></p>)}</div></div></section>)}<section className="award-contact"><h2>Need support with your prompts?</h2><p>So, get in touch with me, and let's make it happen! I'm currently seeking interesting AI projects and promising prompt challenges.</p><a className="button button--accent" href="/contact">Contact me</a></section></article></main>;
}
